language: node_js
dist: trusty
node_js:
  - "6"
  - "8"
services:
  - mongodb
  - redis-server
env:
  - MONGOHQ_URL=mongodb://localhost:27017/jsonresume-tests
git:
  submodules: false
  depth: 10
before_install:
  - git submodule update --init --recursive
before_script:
  - echo Give MongoDB time to start accepting connections
  - sleep 15
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/45ac156371db25c81ab9
    on_start: always
sudo: false   # use container-based architecture; starts up faster
